### ISSUE TITLE
UPDATE API 3.0.0

### ISSUE THREAD

**Issue by teracube** [SpecterTeam/ProxyChecker#2]
please update API 3.0.0  and 4.0.0
thanks

**Comment by OGFris** [comment]
Working on it!

**Comment by teracube** [comment]
@OGFris 
 last commit 3.0.0 have an issue
https://poggit.pmmp.io/r/35772/ProxyChecker_dev-6.phar
I guess it's an unfinalized version

thanks

**Comment by teracube** [comment]
@OGFris 
i suggest you add in config a bypass-check like VPNGuard plugin
```
# Allow users to connect if API Server encounters any errors (Such as Timeout)?
bypass-check: false
```

**Comment by OGFris** [comment]
The player won't get kicked if the task fails, it will just show an error that won't affect anything.

**Comment by teracube** [comment]
@OGFris
ok thanks
